### ISSUE TITLE
JZCommitManager.m line 66

### ISSUE THREAD

**Issue by JustZhtFabric** [JustinFincher/GitHubContributionsiOS#10]
#### in -[JZCommitManager refresh]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/justin-finchers-projects/ios/apps/com.justzht.githubcontributions/issues/5870c8ca0aeb16625bd9cf7e](https://fabric.io/justin-finchers-projects/ios/apps/com.justzht.githubcontributions/issues/5870c8ca0aeb16625bd9cf7e)

**Comment by JustinFincher** [comment]
Fixed in version 1.0.3 (793) by https://github.com/JustinFincher/GitHubContributionsiOS/commit/99e6adc8ab73bf8ced14d0f6624b81c4e8840e17
