### ISSUE TITLE
Dark mode support on Widget (since iOS 13)

### ISSUE THREAD

**Issue by NathanFallet** [JustinFincher/GitHubContributionsiOS#14]
Hello,
It could be great to update the app to support dark mode and submit a new build to the App Store (new version).
Applying suggested changes when the project is opened in Xcode 11 and building with it (with latest SDK) should make it.

**Comment by JustinFincher** [comment]
Hi! Please refer to this: https://github.com/JustinFincher/GitHubContributionsiOS/issues/15#issuecomment-758597931
