### ISSUE TITLE
Memory concerns: "Program ended with exit code: 0"

### ISSUE THREAD

**Issue by KevinGAleman** [JustinFincher/GitHubContributionsiOS#2]
Most times that I try to load and deploy the widget, it says "Unable to load" on the Today screen, and the above message prints to the debugger output.

The error seems to appear after this block gets called in TodayViewController.m.
```objc
        [_commitSceneView refreshFromCommits:weeks];
        [_commitImageView refreshFromCommits:weeks];
```

**Comment by KevinGAleman** [comment]
Adding on to this, it looks like `didReceiveMemoryWarning` regularly gets called in TodayViewController.m, which is likely contributing to the problem.

**Comment by JustinFincher** [comment]
Can you provide more information like what device are you using, and what version of iOS 10? This widget runs well on my iPhone 5S / 6S with 7MB memory usage, but I did hear people saying it takes too much memory and crashes, so I wonder if this is a problem that differs on different device / OS version. Maybe some version of iOS 10 has a more strict memory policy on today extension, or some version of iOS 10 will take more memory when using SceneKit, I just don't have enough information to know which is true.

**Comment by Cee** [comment]
> UIView CALayer storage is twice the size on the 7 Plus by default, so every button took twice the memory, and blew past widget memory limit.

Ref: https://twitter.com/jamesthomson/status/777284708254244864

**Comment by KevinGAleman** [comment]
@JustinFincher @Cee I am using an iPhone 7 Plus running iOS 10.1.1. Cee is correct, and I've verified that the PR does seem to address this issue with no crash, though I still get a memory warning.
